### ISSUE TITLE
need to make modle file for migration data

### ISSUE THREAD

**Issue by rippleFCL** [rippleFCL/kitchen-management-system#1]
so need to make a model.py file with the right object layout for the orm in the database/migration_dat directory, so alembic can migrate the database as this is currently broken. the docker config needs to be updated so it stops using the model file/data from the barcode service and just uses this new model.py file for migrations

**Comment by rippleFCL** [comment]
also alembic config need to be changed to reference this new modle file

**Comment by vurlisium** [comment]
I'll do the model file if you do the alembic and docker files.

**Comment by vurlisium** [comment]
[Mentioned code](https://github.com/ditrames/kitchen-management-system/blob/deb506caaf85ac9c4b42941b9ce9ee709ea2d53f/application/barcode/models.py#L17-L28)

Do you want to Consolidated these two tables into one table, Called stock_tracker?

**Comment by rippleFCL** [comment]
sure, can you also call the table StockTracker? also make that change in all outher depending files you  also need to conver the flask-sqlachemy syntax to plain sqlalchamy

**Comment by rippleFCL** [comment]
can you move the model.py file inside /application/database/migration_dat/migration/dbmodledata because if this is done none of the alembic config need to be changed thank you!
